version: "2"

services:
  dockem-dnsmasq:
    image: andyshinn/dnsmasq
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    command: --log-facility=-
    volumes:
      - ./data/etc/dnsmasq.conf:/etc/dnsmasq.conf
    network_mode: "bridge"
    restart: always

  dockem-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    # labels:
    #   - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      # - ./data/etc/nginx/certs:/etc/nginx/certs
      # - ./data/etc/nginx/vhost.d:/etc/nginx/vhost.d
      # - ./data/usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: "bridge"
    restart: always

  # dockem-ssl:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   container_name: dockem-ssl
  #   volumes_from:
  #     - dockem-proxy
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   restart: always
  #   network_mode: "bridge"

